language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: hermanmiller.dkr@gmail.com
  on:
    tags: true
  api_key:
    secure: BZzGYosFDRySlXtSxjvEUHkaXhxLcKfA3/3z4J/2KKrGkbjhxRrPq2pftrHTdQHcfedBb4csZRxc/smgqwrHmdayvHOCokgBhYJS5MNRsAEBIvAMGxUARmbYLRFXBvLD8p6w9vEALTVj6mjlyc23LHbuGlFJnryH7F0lUFMAshQSw+T9GJkqVxOTYZnI7kvCCEKqzKyz9Tt+EJPASntZyIRq+M0i0pXW6UlVdh8FUy0agBWTzk/MozJx/XGfO90O46YUphnEJg/8cGuKkrvJMKaPBuHyW0KHheOpGtqjK/98kkxV9w9uL+YGUKVExsIWvf1IVI5kftHlKGLagC5J0k9LkVuAhSHdSgenEaj/zONSQ1vepcCVEQ1PuJhv3XL2ozEyG6EkTqOuEH7VAqdY/pkpbNkH/2J2SVps5+1L6AqvxgC3rA5xs0Vp8bmS3kp/4BMAFwNOlT2WH7TtvnS0X4x4SByTAZtIL8VrGUnpcb1X7Tww8M3alfdAfI0RZxDV8R/KtcDktjNiGLfLp9NR4wzYDK4abx6zksPahrNzAPh4f6IqprQpethQUr5cxip7D0rxkcvbZUGnZC7/thtZyXU92Igz4I9FqM6CHDLbxL2RNz0IBi9lgPwBuUYyQfJvAMp8UDN5O1cG9l6x1QSZKe3EjrqMkOEK6uUEvZcScFs=
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js