name: Test and Build
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['10.x', '12.x', '14.x', '16.x', '22.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: 'macos-13'
            node: '10.x'
          - os: 'macos-13'
            node: '12.x'
          - os: 'macos-13'
            node: '14.x'
        exclude:
          - os: 'macos-latest'
            node: '10.x'
          - os: 'macos-latest'
            node: '12.x'
          - os: 'macos-latest'
            node: '14.x'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2
        
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build
        run: yarn build
